### ISSUE TITLE
Using @eventType does not work

### ISSUE THREAD

**Issue by stramel** [nikhilmodak/gulp-ngdocs#18]
Per [documentation][1] `@eventType` should be either `emit` or `broadcast`. It appears that the existing is checking for `on`

[1]: https://github.com/angular/angular.js/wiki/Writing-AngularJS-Documentation#angularjs-specific-ngdoc-directives

**Comment by admwx7** [comment]
To be exact, it's looking for `/^([^\s]*)\s+on\s+([\S\s]*)/`

`/^([^\s]*)\s+` should probably be something more like `/^(\s*)`, though it's later used as the type which doesn't make sense as `@eventType` doesn't use a type according to the ngdocs documentation.

The check for on shouldn't be there according to the documentation, but can be resolved with a `?` to make it optional for backwards compatibility.

`([\S\s]*)/` is going to require the string 'b r o a d c a s t ' if I'm not mistaken and should instead be `([\S]*)/` to grab the last word then ignore everything ever it.  To better enforce the documentation a `(broadcast|emit)` would work best imo.

**Comment by stramel** [comment]
Seems to be the correct functionality according to dgeni documentation
