### ISSUE TITLE
Error: Don't know how to format @ngDoc: module

### ISSUE THREAD

**Issue by rozza2058** [nikhilmodak/gulp-ngdocs#20]
No formatting (and therefore documentation pages) available for modules. Any reason this is the case?

**Comment by MikaAK** [comment]
+1 This seems like a weird issue, how are we supposed to group services.

**Comment by nikhilmodak** [comment]
You can use `overview` tag for documenting modules. Please refer to https://github.com/angular/dgeni-packages/blob/master/NOTES.md#ngdoc-tags

**Comment by surfjedi** [comment]
That doesn't seem to group them together?

**Comment by surfjedi** [comment]
angular.module('common.analytics', ['common.moment', 'common.d3Service'])
/**
   *  @ngdoc overview
   *  @name common.analytics
   *
   *  @requires common.moment
   *  @requires common.d3Service
   *
   *  @description
   *  enter description using overview
   *
   *  @example
   *  enter example
   */
  .service('analyticsService', function analyticsService(API, $http, dateService, d3Service) {
  /**
   *  @ngdoc service
   *  @name analyticsService
   *  @requires ng.$http
   *  @requires API
   *  @requires dateService
   *  @description uses service
   */

**Comment by surfjedi** [comment]
![api_documentation__common_services_animations](https://cloud.githubusercontent.com/assets/536809/9120539/1651da42-3c3a-11e5-8cc0-54c3810c1b94.png)

**Comment by surfjedi** [comment]
Note at the top the analytics are in separate groups, the only way I can get them to group together is names common.services.module, but it can't auto group the child services form modules.
