### ISSUE TITLE
Doc sample does not work

### ISSUE THREAD

**Issue by jseto** [nikhilmodak/gulp-ngdocs#23]
The doc sample passing nothing to `process` method, throws an exception

>TypeError: Cannot read property 'loadDefaults' of undefined

```
gulp.task('ngdocs', [], function () {
  var gulpDocs = require('gulp-ngdocs');
  return gulp.src('path/to/src/*.js')
    .pipe(gulpDocs.process())
    .pipe(gulp.dest('./docs'));
});
```

**Comment by nikhilmodak** [comment]
Duplicate https://github.com/nikhilmodak/gulp-ngdocs/issues/21
