### ISSUE TITLE
Add more collaborators

### ISSUE THREAD

**Issue by andyperlitch** [nikhilmodak/gulp-ngdocs#26]
Hi @nikhilmodak,

First off, thanks for the great project; it has been very beneficial for the project I am working on and I am sure others benefit greatly as well.

Having said that, it appears that you are relatively inactive on github and as a result, issues and PRs go unaddressed for sometimes weeks at a time. I would like to offer my help in sharing the burden of management on this library (merging pull requests, answering questions), especially since now I have had a chance to dig in to the code base and write a test, etc. 

The open-source community would benefit quite a bit if you allowed people like myself to become collaborators.

Regards,
Andy

**Comment by nikhilmodak** [comment]
Hello @andyperlitch, first of all thank you for contributing to gulp-ngdocs and my apologies for delay in responding to the PRS. I appreciate your interest in helping me manage the repository. I have added you to collaborators of the repository!

Thanks,
Nikhil

**Comment by andyperlitch** [comment]
Thanks @nikhilmodak! I'm looking into the open issues now, so adding me is already paying off :-)
