### ISSUE TITLE
Document application stop when it failed to load modules

### ISSUE THREAD

**Issue by nhducit** [nikhilmodak/gulp-ngdocs#27]
error occur in these lines:

```
  element.bind('$destroy', function() {
    deregisterEmbedRootScope();
    embedRootScope.$destroy();
  });
```

solution: I think we need to check undefined before execute function

``` js
element.bind('$destroy', function() {
  if(deregisterEmbedRootScope){
    deregisterEmbedRootScope()
  }

  if(embedRootScope){
    embedRootScope.$destroy();
  }
});
```

**Comment by andyperlitch** [comment]
@nhduc296  Can you give a little context as to when this error occurs?

**Comment by fkloepf** [comment]
hi, i've got the same problem in version 0.2.13

randomly I get an error `TypeError: deregisterEmbedRootScope is not a function` when switching between different pages.

The example from the readme file has the same error if you add a few mock modules and functions.

The error occurs randomly after switching between the pages via the menu on the left side after 0-25 page  switches.

**Comment by fkloepf** [comment]
@andyperlitch what's the status with this bug? Do you need more informations?

**Comment by fabiotisci** [comment]
Same error here. I get that error when I surf in between links generated in the docs. But I also get:
Error: [ngRepeat:dupes] 
http://errors.angularjs.org/1.3.20/ngRepeat/dupes?p0=page%20in%20module.dir…A%22%23%2Fapi%2Fcpp-ui-spa-master.routes.case-information%3Aevidence%22%7D
    at Error (native)
    at http://localhost:63342/ui-app/dist/docs/js/angular.min.js:6:417
    at http://localhost:63342/ui-app/dist/docs/js/angular.min.js:235:172
    at Object.fn (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:123:20)
    at n.$digest (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:124:114)
    at n.$apply (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:127:12)
    at http://localhost:63342/ui-app/dist/docs/js/angular.min.js:17:479
    at Object.e [as invoke] (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:36:315)
    at d (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:17:400)
    at tc (http://localhost:63342/ui-app/dist/docs/js/angular.min.js:18:179)

I'm using Angular 1.5.3
