### ISSUE TITLE
Error on running ngdocs

### ISSUE THREAD

**Issue by Zizzamia** [nikhilmodak/gulp-ngdocs#30]
I try to set my gulpfile in this way
```js
gulp.task('ngdocs', [], function () {
  return gulp.src('./src/**/*.js')
    .pipe(gulpDocs.process({}))
    .pipe(gulp.dest('./docs2'));
});
```
and after opening `docs2/index.html` on the console log I get this error.
![error](https://cloud.githubusercontent.com/assets/829214/6117091/07f1ab3a-b067-11e4-9f86-4a064307775e.jpg)
```js
TypeError: Cannot read property 'replace' of undefined
    at Gb (angular.js:10564)
    at Me.$get (angular.js:11374)
    at Object.e [as invoke] (angular.js:4185)
    at angular.js:4003
    at d (angular.js:4144)
    at Object.e [as invoke] (angular.js:4176)
    at angular.js:4003
    at d (angular.js:4144)
    at Object.e [as invoke] (angular.js:4176)
    at angular.js:6485
```

**Comment by rolandpeelen** [comment]
+1 Same issue

**Comment by designermax** [comment]
https://github.com/m7r/grunt-ngdocs/issues/67

**Comment by codecadwallader** [comment]
Agree, that resolved the issue for me.  To make that more explicit, the problem is with serving the files locally over the file:// protocol and that not working with AngularJS.  More details here: http://stackoverflow.com/questions/16251420/couldnt-load-template-using-templateurl-in-angularjs

**Comment by Zizzamia** [comment]
Will be nice have a minimum of documentation to how run a simple HTTP web server to run the docs.

**Comment by andyperlitch** [comment]
@Zizzamia agreed. I'll put that in the readme.
