### ISSUE TITLE
add more ngdoc directives

### ISSUE THREAD

**Issue by yahyaKacem** [nikhilmodak/gulp-ngdocs#36]
use [the dgeni-packages](https://github.com/angular/dgeni-packages) from angular repository to add possibilities to use more ngdoc directives like in [here](https://github.com/angular/dgeni-packages/blob/master/NOTES.md#ngdoc-tags).

example to be able to do this:

``` javascript
    /*
   * @ngdoc module
   */
```

**Comment by andyperlitch** [comment]
Couldn't agree more. We have been running into this issue in our project that uses ngdocs. I'll take a look when possible, but am certainly open to community contribution!

**Comment by hellfrom** [comment]
+1

**Comment by Smolations** [comment]
:+1: for this.
