### ISSUE TITLE
ECONNREFUSED Request to    https://bower.herokuapp.com/packages/angular failed: connect ECONNREFUSED

### ISSUE THREAD

**Issue by ajbogh** [nikhilmodak/gulp-ngdocs#42]
The request to install bower-angular is breaking my builds because it's attempting to access a resource outside of our allowed list of domains. Please include angular in the package.json file instead.

npm install angular

bower angular#~1.3.1      ECONNREFUSED Request to    https://bower.herokuapp.com/packages/angular failed: connect ECONNREFUSED
npm ERR! gulp-ngdocs@0.2.10 install: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gulp-ngdocs@0.2.10 install script.
npm ERR! This is most likely a problem with the gulp-ngdocs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls gulp-ngdocs
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 2.6.32-504.3.3.el6.x86_64
npm ERR! command "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/grunt_bower_karma_yo/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/grunt_bower_karma_yo/bin/npm" "install"
npm ERR! cwd /opt/jenkins_jobs/hal-secondaryFlow-RELEASE/workspace
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE

**Comment by dschwank** [comment]
Hey,
during the installation of the `gulp-ngdocs` module it finally calls the standard `bower` component to install the required js packages. Furthermore it installs also other packages like `marked` or `google-code-prettify`. If the `bower.herokuapp.com` domain is not reachable from your network, check if you need to specify a special proxy or something else.
Therefore just change (or create) the [`.bowerrc`](http://bower.io/docs/config/#bowerrc-specification) file:
```js
  {
    "registry": {
      "search" : [ "YOUR_BOWER_REGISTRY", "GLOBAL_BOWER_REGISTRY" ],
      "register" : "YOUR_BOWER_REGISTRY"
    },
    "proxy": "YOUR_HTTP_PROXY",
    "https-proxy": "YOUR_HTTPS_PROXY"
  }
```
If you want to use another `bower-registry` just use the `registry.search` property in the example and change it to what you want.

I hope this answer fixes your problem with the `gulp-ngdocs` module.

Greetings!

**Comment by andyperlitch** [comment]
@ajbogh: @dschwank is correct. We'd rather not check in library code like this.

@dschwank thanks for all your help lately!

**Comment by ajbogh** [comment]
Thanks!
