### ISSUE TITLE
No docs folder gets created

### ISSUE THREAD

**Issue by samirgit** [nikhilmodak/gulp-ngdocs#44]
```javascript
var gulp = require('gulp');
gulp.task('ngdocs', [], function () {
  var gulpDocs = require('gulp-ngdocs');
  var options = {
     scripts: [
		'./www/lib/ionic/js/angular/angular.min.js',
		'./www/lib/ionic/js/angular/angular.min.js.map',
		'./www/lib/ionic/js/angular-animate/angular-animate.min.js',
		'./www/lib/ionic/js/angular-animate/angular-animate.min.js.map'
	],
    html5Mode: false
  }
  return gulp.src('.www/app/directives.js')
    .pipe(gulpDocs.process(options))
    .pipe(gulp.dest('./docs'));
});
```
i run gulp ngdocs and it starts ngdocs and ends and nothing happens!

**Comment by dschwank** [comment]
Hey,

is it maybe just a typo in your script? `gulp.src` directs to a folder named `.www` and not `www` - the slash for the directory is missing (`./www/app/directives.js`). Otherwise - can you post the command-line output?

Greetings!

**Comment by andyperlitch** [comment]
@samirgit I am guessing that @dschwank is correct. Change the line `return gulp.src('.www/app/directives.js')` to `return gulp.src('./www/app/directives.js')`.

**Comment by samirgit** [comment]
@dschwank  true it was a type .. had a long day trying to make gulp run on my machine .. 
had problems with installing ngdocs globaly was getting  error:
Error: EACCES, permission denied '/Users/samirkhattar/.config/configstore/bower-github.yml'
You don't have access to this file.
and tried everything from chmod to erasing and readding file, --allow-root and everything gulp-ngdocs was not getting installed globaly so i installed it inside the project.. 
so in the end i switched to grunt lol 

but now gulp-ngdocs also works .. so donno wich one to use. :D thanks anyway
