### ISSUE TITLE
Publish latest versions to npm

### ISSUE THREAD

**Issue by andyperlitch** [nikhilmodak/gulp-ngdocs#47]
@nikhilmodak, the last two versions of gulp-ngdocs have not been published to npm because I am not an owner on the npm registry. Can you please publish them yourself or add me by using [this command](https://docs.npmjs.com/cli/owner)?

Thanks!
-Andy

**Comment by hellfrom** [comment]
+1

**Comment by andyperlitch** [comment]
@nikhilmodak any update on this?

**Comment by nikhilmodak** [comment]
Hey @andyperlitch I have published the latest versions on npm and also added you as a collaborator on npm! Thanks for your contributions.
