### ISSUE TITLE
Remove bower dependencies, or run bower install with allow-root

### ISSUE THREAD

**Issue by michaelbazos** [nikhilmodak/gulp-ngdocs#49]
When node is running as a root user, the `bower install` command triggered by the install script is causing the following error : 

```sh
bower ESUDO         Cannot be run with sudo
[...]
npm ERR! gulp-ngdocs@0.2.12 install: `bower install`
```

Couldn't the actual bower dependencies be managed in package.json instead, or at least the `bower install` command launched with the `--allow-root` option?

**Comment by willpracht** [comment]
[Check this out, my friend](http://hood.ie/blog/why-you-shouldnt-use-sudo-with-npm.html). 

Cheers.

**Comment by willpracht** [comment]
Why are you running `node` via `sudo`?

**Comment by michaelbazos** [comment]
This `npm install` is executed on a distant host I don't control, hard to guess why it is ran as root. 
Anyway, I see that **[v0.12.3](https://github.com/nikhilmodak/gulp-ngdocs/commits/v0.2.13)** moved bower dependencies to `package.json`, therefore the issue is solved.
