### ISSUE TITLE
Working with gulp.watch

### ISSUE THREAD

**Issue by andyperlitch** [nikhilmodak/gulp-ngdocs#6]
Hey @nikhilmodak ,

Great tool, thanks for this! I am trying to get this to work with a watch command, e.g.:

``` JavaScript
gulp.task('ngdocs', [], function () {
  var options = {
    html5Mode: false
  };
  var ngdocs = require('gulp-ngdocs');
  return gulp.src(['my/scripts/**/*.js'])
    .pipe(ngdocs.process(options))
    .pipe(gulp.dest('./ngdocs'))
    .on('error', function(err) {
      console.log('Error from ngdocs: ', err);
    });
});

gulp.task('serve:ngdocs', function(next) {
  var server = express();
  var port = argv.p || 9002;
  server.use(express.static('ngdocs')).listen(port, next);
  console.log('Docs being served at http://localhost:' + port);

  // this here:
  gulp.watch(dev.scripts.src, ['ngdocs']);
});
```

However the problem is that each time the ngdoc task above is run, things get double-added. So the first time it runs, everything is great (note that I have added a log statement [here](https://github.com/nikhilmodak/gulp-ngdocs/blob/master/src/templates/js/docs.js#L215) for illustration):

![image](https://cloud.githubusercontent.com/assets/1390651/4939075/403ed80a-65d0-11e4-82bb-d678e605deae.png)

But on the next time ngdoc gets triggered by the watch, it has been doubled and there is an ng-repeat error:

![image](https://cloud.githubusercontent.com/assets/1390651/4939130/91a33de4-65d0-11e4-8669-1759ac877815.png)

I've been digging through your code for a good while (because I normally like to open pull requests, not issues) but I am pretty stumped. I am guessing that because `require()` in node [caches the module](http://nodejs.org/api/modules.html#modules_caching), some state is being kept somewhere like an array of files that just gets added to rather than cleared on every call to `processDoc`.

Any suggestions?

Thanks!
Andy

**Comment by smdahlen** [comment]
This issue has appeared to regress in 0.2.7.

**Comment by andyperlitch** [comment]
argh! im going to open a PR with a freaking test so this doesnt happen again

**Comment by andyperlitch** [comment]
@smdahlen i just opened #25 which should not only fix this, but also has a test to make sure it doesnt break again
