### ISSUE TITLE
@ngdoc filter and others

### ISSUE THREAD

**Issue by Freezystem** [nikhilmodak/gulp-ngdocs#63]
Hi, I'm trying to add a filter to the doc. I've tried a lot a different syntax with no success. Here is my code:

```javascript
/**
 * @ngdoc filter
 * @name myModule.filter:thousandSeparator
 * @function
 * @description
 * Add a space as a thousand separator to a string, every 3 char. Start from the end.
 *
 *
 * @param {String} string
 * String to parse
 * @returns {String} parsed input string
 */
```

I also notice in the generated pages that there are other properties of the main module I can't populate:

```javascript
{  
    "name"          : "myModule",
    "url"           : "#/api/myModule",
    "globals"       : [  ],      //this one
    "controllers"   : [  ],
    "directives"    : [  ],
    "services"      : [  ],
    "others"        : [  ],
    "types"         : [  ],      //this one
    "filters"       : [  ]       //and this one
}
```

Can someone tell me how to access it ?

**Comment by cpaof** [comment]
Have a look at how filters are documented in AngularJS itself. Maybe that helps? https://github.com/angular/angular.js/blob/g3_v1_3/src/ng/filter/filters.js

**Comment by Freezystem** [comment]
Yeah I already tried that yet. But it's not working, maybe because they are using [dgeni](https://github.com/angular/dgeni) not `gulp-ngdocs`. Thanks for this hint by the way.

**Comment by Freezystem** [comment]
@nikhilmodak Any hint on this question ? I have looked at the `src/ngdoc.js` file and I'm feeling like `title()` is not parsing filters, although it's parsed through `MODULE_CUSTOM` regex but I'm unable to figure out how to declare it.

**Comment by bampakoa** [comment]
@Freezystem what exactly is not working using a filter in the docs? Can you give as a hint or show some snippet?

**Comment by Freezystem** [comment]
Hi @bampakoa i'm not working on this project anymore but I can describe my issue from memory. 

By the time I was writing my project documentation I wasn't able to describe my filters, as they weren't displayed in the generated doc in a proper filter section of the right menu. Types and globals weren't displayed either.

**Comment by bampakoa** [comment]
FYI, I have checked with the latest version of the plugin and filters work fine. In case you use it again and face the same problem, ping me and I 'll be glad to help 😄

**Comment by Freezystem** [comment]
Great ! I'll keep you updated if I stumble on this error again. Thanks for your help.
