### ISSUE TITLE
Default file paths are invalid for NPM >= 3 

### ISSUE THREAD

**Issue by mortargrind** [nikhilmodak/gulp-ngdocs#78]
When using default file paths for external script dependencies, these dependencies (like angular or angular-animate) are generated according to old NPM folder structure (which is nested almost always). So when using this plugin with NPM 3 or higher, we get an invalid file path for those libraries because of new NPM's flat folder structure.

**Comment by dougiefresh49** [comment]
I am experiencing the same issue. 
I am sing npm version 3.3.12.

As a temporary solution, @mortargrind I downgraded gulp-ngdocs to v0.2.12. I am not fully aware of the features you lose by doing so but the basic documentation functionality works. 

A better solution would be to adjust for the flat architecture for the newer node versions

**Comment by gumartinm** [comment]
I had the same problem after upgrading to the latest npm version. It would be nice if it worked out of the box (like before) but in the meanwhile I fixed it using the **scripts**  [option](https://github.com/nikhilmodak/gulp-ngdocs#scripts) with the paths to the required scripts.

For example, in my case I am using bower with the following **dependencies**:
```javascript
       "dependencies": {
         "bootstrap": "~3.3.6",
         "font-awesome": "~4.5.0",
         "oclazyload": "~1.0.9",
         "angular-animate": "~1.4.8",
         "angular-bootstrap": "~0.14.3",
         "angular-translate": "~2.8.1",
         "angular-ui-router": "~0.2.15",
         "angular": "~1.4.8"
       }
 ```
The downloaded files will be located in the following paths:
```javascript
      'bower_components/angular/angular.min.js',
      'bower_components/angular/angular.min.js.map',
      'bower_components/angular-animate/angular-animate.min.js',
      'bower_components/angular-animate/angular-animate.min.js.map',
      'bower_components/marked/lib/marked.js'
 ```
So the **scripts** option will end up being like this:

```javascript
      scripts: [
        'bower_components/angular/angular.min.js',
        'bower_components/angular/angular.min.js.map',
        'bower_components/angular-animate/angular-animate.min.js',
        'bower_components/angular-animate/angular-animate.min.js.map',
        'bower_components/marked/lib/marked.js'
      ]
```

**Comment by citi-raulfernandez** [comment]
Hi, is this fix going to be release any time soon?

**Comment by huerlisi** [comment]
A new release has been published a couple days ago with npm 3 support. Could you please test if this is fixed now?
