### ISSUE TITLE
CoffeeScript support

### ISSUE THREAD

**Issue by AlexanderKozhevin** [nikhilmodak/gulp-ngdocs#82]
I wrote comments in coffeScript and compile it in JS. Then I try to run gulp-ngdocs with these compiled files. But CoffeeScript doesn't support non-standard comments. 
So this expression
```
###
# @ngdoc directiverer
# @name rfx.directive:rAutogrow
###
```
is compiled into
```
/*
 * @ngdoc directiverer
 * @name rfx.directive:rAutogrow
 */
```
But in you there is no normal way to set two asterisks in the beginning
_/**_

**Comment by miletsky** [comment]
@AlexanderKozhevin how 'bout this http://stackoverflow.com/a/9157241 ?

**Comment by AlexanderKozhevin** [comment]
@miletsky , Thanx a lot!
NgDocs is a one more step in improvement my gulp production system.
