### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by benjaminsuch** [nikhilmodak/gulp-ngdocs#89]
Hello,

I first had this [issue](https://github.com/nikhilmodak/gulp-ngdocs/issues/79) but could solve it with the solution from @TheCodeDestroyer. But now I'm getting the error:

`TypeError: Cannot read property 'replace' of undefined`

I first thought it had something to do with the angular version but even replacing it with a newer one  didn't solve it. Can someone help?

**Comment by benjaminsuch** [comment]
Okay found the issue. You have to setup a local server to view the docs. The filesystem doesn't work.

**Comment by TheCodeDestroyer** [comment]
Do you still have an issue? Otherwise, just close the task :)

**Comment by benjaminsuch** [comment]
No, no issue anymore :)
