### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by TheCodeDestroyer** [nikhilmodak/gulp-ngdocs#94]
Hey are there any plans to publish the bug fixes that were merged?

**Comment by kwypchlo** [comment]
+1

**Comment by skoszuta** [comment]
+1

**Comment by rdkleine** [comment]
+1

**Comment by huerlisi** [comment]
We just tested the version as current on github. It works perfectly for us, while the version on npm failes due to npm > 3.

Would really appreciate a new release as the current one is broken on npm > 3.

Thanx:-)

**Comment by huerlisi** [comment]
Friendly ping:-)

Is there anything I can help to get this release out? Are there any blocking issues you know about? Are you overloaded with other things and would like to pass over maintainership to someone else?

Anyhow: big thanks for your work on this!

**Comment by andyperlitch** [comment]
Hey @huerlisi, @rdkleine, @TheCodeDestroyer, @skoszuta, @kwypchlo ,

So sorry for the delay guys, no real excuse for it. I've just published 0.3.0, please let me know if there are any issues.
